name: sync-upstream

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Ensure upstream remote and fetch
        run: |
          if ! git remote get-url upstream > /dev/null 2>&1; then
            git remote add upstream https://github.com/iptv-org/epg.git
          fi
          git fetch upstream master
          git fetch origin master

      - name: Fast-forward master from upstream
        id: merge
        run: |
          git checkout master
          if git merge --ff-only upstream/master; then
            AHEAD=$(git rev-list --count origin/master..master)
            echo "merge_changed=$AHEAD" >> "$GITHUB_OUTPUT"
          else
            echo "Fork has diverged from upstream. Manual intervention required." >&2
            exit 1
          fi

      - name: Push changes to origin
        if: steps.merge.outputs.merge_changed != '0'
        run: git push origin master
